### ISSUE TITLE
Feat: Display graph of "Minecraft mod downloads per game version, per mod loader"

### ISSUE THREAD

**Issue by skyjay1** [CurseForgeCommunity/CFLookup#8]
Suggestion: add a graph that shows the *approximate download count* of CurseForge mods per Minecraft version, per mod loader.
This information will help modders and modpack creators decide which version to target for which mod loader.

**Comment by itssimple** [comment]
Sorry for the delay in response.

Sure, it can be done, but I'll have to rework how CFLookup works a bit first, so that I can handle background jobs a bit better, and then store that data somehow.

The current stats are fetched live and stored in a memory cache (redis) for a short period of time.
But this would need to be fetched in the background, processed and then stored in a good way for me to be able to fetch it without too much delay.

But I like the idea of it.

**Comment by itssimple** [comment]
As the paging results is limited to 50k, I cannot in any good way, get a download stat per modloader, so I can't do this issue, as the API works right now.

**Comment by skyjay1** [comment]
Why not do multiple API calls? The first 50k results, then the next 50k results, etc? That’s what pagination is for, right?
